name: Update Progress

on:
  push:
    paths:
      - '**/*'
  schedule:
    - cron: '0 12 * * *'   # runs daily at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute totals
        id: calc
        shell: bash
        run: |
          GOAL=150
          # Count top-level dirs whose names start with a digit
          SOLVED=$(find . -maxdepth 1 -type d -regex './[0-9].*' | wc -l | xargs)
          PCT=$(( 100*SOLVED/GOAL ))
          echo "goal=$GOAL" >> $GITHUB_OUTPUT
          echo "solved=$SOLVED" >> $GITHUB_OUTPUT
          echo "pct=$PCT" >> $GITHUB_OUTPUT
          echo "date=$(date -u +"%b %d, %Y")" >> $GITHUB_OUTPUT

      - name: Rewrite README block
        shell: bash
        run: |
          awk -v solved="${{ steps.calc.outputs.solved }}" \
              -v goal="${{ steps.calc.outputs.goal }}" \
              -v pct="${{ steps.calc.outputs.pct }}" \
              -v today="${{ steps.calc.outputs.date }}" '
            BEGIN { inside=0 }
            /<!-- PROGRESS_START -->/ {
              print; inside=1;
              print "<div align=\"center\">\n"
              print "  <img src=\"https://img.shields.io/badge/Solved-" solved "-22c55e?style=for-the-badge\" alt=\"Solved\">"
              print "  <img src=\"https://img.shields.io/badge/Streak-1_day-3b82f6?style=for-the-badge\" alt=\"Streak\">"
              print "  <img src=\"https://img.shields.io/badge/Goal-" goal "_problems-8b5cf6?style=for-the-badge\" alt=\"Goal\">\n"
              print "  <div style=\"margin-top:14px;background:#1f2937;border-radius:10px;width:520px;height:16px;display:inline-block;\">"
              print "    <div style=\"background:linear-gradient(90deg,#22c55e,#3b82f6);height:16px;width:" pct "%;border-radius:10px;\"></div>"
              print "  </div>\n"
              print "  <div style=\"margin-top:8px;font-weight:600;\">" solved " / " goal " problems • 1-day streak</div>"
              print "  <div style=\"margin-top:4px;font-size:12px;color:#9ca3af;\">Updated: " today "</div>\n"
              print "</div>";
              next
            }
            /<!-- PROGRESS_END -->/ { print; inside=0; next }
            inside==0 { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update progress bar to ${{ steps.calc.outputs.pct }}%"
            git push
          fi
